client_config_backend: file
client_config:
    client_id: "87674759229-nilht47fgfcv2n0qj0mes13pn3ib96vq.apps.googleusercontent.com"
    client_secret: "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"

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install